export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_TTL_SECONDS: 900, // 15 minutes
  REFRESH_TOKEN_TTL_SECONDS: 2592000, // 30 days
  BCRYPT_COST_FACTOR: 12,
  MAX_LOGIN_ATTEMPTS_PER_MINUTE: 5,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
} as const;
