export const GAME_CONSTANTS = {
  MIN_PLAYERS: 3,
  MAX_PLAYERS: 10,
  DEFAULT_ROUND_TIME_SECONDS: 30,
  DEFAULT_TOTAL_ROUNDS: 5,
  BOT_BACKFILL_DELAY_MS: 30000,
  ROOM_EXPIRY_SECONDS: 3600,
  MAX_IDLE_TIME_SECONDS: 120,
} as const;

export const MATCHMAKING_CONSTANTS = {
  INITIAL_RATING_RANGE: 100,
  EXPAND_INTERVAL_MS: 5000,
  EXPAND_AMOUNT: 50,
  MAX_WAIT_MS: 30000,
  DEFAULT_SKILL_RATING: 1000,
  MIN_SKILL_RATING: 0,
  MAX_SKILL_RATING: 3000,
} as const;

export const SCORING_CONSTANTS = {
  MAJORITY_BONUS: 100,
  SPEED_BONUS_MAX: 50,
  STREAK_MULTIPLIER: 0.1,
  WIN_XP: 50,
  LOSS_XP: 20,
  PARTICIPATION_XP: 10,
} as const;
